backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - name: "events"
    label: "Events"
    folder: "src/eventposts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g.,
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Artist", name: "artist", widget: "string" }
      - { label: "Tags",  name: "tags", widget: "list", default: ["post"] }
      - { label: "Location", name: "location", widget: "map" }
      - { label: "Image", name: "image", widget: "image"}
      - { label: "Image caption", name: "imageAlt", widget: "string" }